apiVersion: v1
kind: Service
metadata:
  name: flask-aws-service
  labels:
    app: flask-aws-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: flask-aws-app
