apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-aws-app
  labels:
    app: flask-aws-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-aws-app
  template:
    metadata:
      labels:
        app: flask-aws-app
    spec:
      containers:
      - name: flask-aws-app
        image: nanosharkdevops/flask-aws:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-key
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5




